import { ConferenceEventType } from '@/types/ScheduleTypes';

export const conferenceSchedule: ConferenceEventType[] = [
    // === PANEL STAGE ===
    {
        date: new Date("2026-03-20T09:30:00"),
        name: "Privacy in Payments",
        icon: "panel",
        duration: 0.75,
        stage: "panel",
    },
    {
        date: new Date("2026-03-20T10:30:00"),
        name: "CBDCs and their Frameworks",
        icon: "panel",
        duration: 0.75,
        stage: "panel",
    },
    {
        date: new Date("2026-03-20T11:30:00"),
        name: "L1s & L2s in Payments",
        icon: "panel",
        duration: 0.75,
        stage: "panel",
    },
    {
        date: new Date("2026-03-20T14:00:00"),
        name: "Regulatory Landscape & Compliance",
        icon: "panel",
        duration: 0.75,
        stage: "panel",
    },
    {
        date: new Date("2026-03-20T15:00:00"),
        name: "Real-World Adoption & Merchant Integration",
        icon: "panel",
        duration: 0.75,
        stage: "panel",
    },
    {
        date: new Date("2026-03-20T16:00:00"),
        name: "How Can Banks Create a DeFi Strategy?",
        icon: "panel",
        duration: 0.75,
        stage: "panel",
    },

    // === KEYNOTE STAGE ===
    {
        date: new Date("2026-03-20T09:30:00"),
        name: "AlphaTON - Data Sovereignty, Take Back Control: Blockchain in the Age of AI",
        icon: "keynote",
        duration: 0.33,
        speaker: "William De Ath",
        stage: "keynote",
    },
    {
        date: new Date("2026-03-20T10:15:00"),
        name: "AAVE ACI Team",
        icon: "keynote",
        duration: 0.75,
        speaker: "Nandy",
        stage: "keynote",
    },
    {
        date: new Date("2026-03-20T11:00:00"),
        name: "On-Chain Treasury - United Nations Transformation: Adoption of Blockchain Technology, Tokenisation, and use of Stablecoins",
        icon: "keynote",
        duration: 0.75,
        speaker: "Carmen Hett X William De Ath",
        stage: "keynote",
    },
    {
        date: new Date("2026-03-20T11:45:00"),
        name: "Belem - From Experiment to Infrastructure: How Institutional Capital Is Reshaping DeFi",
        icon: "keynote",
        duration: 0.75,
        speaker: "Stanislas de Maistre",
        stage: "keynote",
    },
    {
        date: new Date("2026-03-20T13:00:00"),
        name: "CMTAT",
        icon: "keynote",
        duration: 0.25,
        speaker: "Rosie x Ryan",
        stage: "keynote",
    },
    {
        date: new Date("2026-03-20T13:15:00"),
        name: "SwissBorg",
        icon: "keynote",
        duration: 0.75,
        speaker: "Nicolas Rémond",
        stage: "keynote",
    },
    {
        date: new Date("2026-03-20T14:00:00"),
        name: "Hyli",
        icon: "keynote",
        duration: 0.75,
        speaker: "Lancelot de Ferrière",
        stage: "keynote",
    },
    {
        date: new Date("2026-03-20T14:45:00"),
        name: "Areta x Storm - M&A and the Future of Payments",
        icon: "keynote",
        duration: 0.75,
        speaker: "Sheraz Ahmed x Timothy Voirol",
        stage: "keynote",
    },

    // === TECHNICAL STAGE ===
    {
        date: new Date("2026-03-20T10:30:00"),
        name: "Ephemeral Coin Tracing",
        icon: "technical",
        duration: 0.75,
        speaker: "François-Xavier Wicht",
        stage: "technical",
    },
    {
        date: new Date("2026-03-20T11:15:00"),
        name: "Programmable Money: How Stablecoins Replace the Backend of Asset Management",
        icon: "technical",
        duration: 0.75,
        speaker: "Marc Bickel",
        stage: "technical",
    },
    {
        date: new Date("2026-03-20T13:15:00"),
        name: "PopCoin, a Democratic Time-Based Cryptocurrency",
        icon: "technical",
        duration: 0.75,
        speaker: "Prof. Bryan Ford",
        stage: "technical",
    },
    {
        date: new Date("2026-03-20T14:00:00"),
        name: "Offline Use of Stablecoins at Time of War or Natural Disaster",
        icon: "technical",
        duration: 0.75,
        speaker: "Dr. habil. Jean-Marc Seigneur",
        stage: "technical",
    },
    {
        date: new Date("2026-03-20T14:45:00"),
        name: "An Arbitrary Mean-Rate Exchange Protocol",
        icon: "technical",
        duration: 0.75,
        speaker: "Mark Richardson",
        stage: "technical",
    },
    {
        date: new Date("2026-03-20T15:30:00"),
        name: "The Invisible Infrastructure: How Stablecoins Are Quietly Rebuilding Global Payments",
        icon: "technical",
        duration: 0.75,
        speaker: "Dr. Anandadeep Mandal",
        stage: "technical",
    },
];
